apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flashservice-api-ingress
  namespace: flashservice
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flashservice-health-ingress
  namespace: flashservice
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /users/(health|db/health)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 80
          - path: /orders/(health|kafka/health)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service
                port:
                  number: 80
