apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: flashservice
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-init
          image: apache/kafka:4.2.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              for i in $(seq 1 30); do
                /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka.flashservice.svc.cluster.local:9093 && break
                echo "Retry $i..."
                sleep 2
              done
              echo "Creating Kafka topics..."
              /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic user-db-cdc --partitions 3 --replication-factor 1 --bootstrap-server kafka.flashservice.svc.cluster.local:9093
              /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic email-job --partitions 3 --replication-factor 1 --bootstrap-server kafka.flashservice.svc.cluster.local:9093
              /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic failed-dlq --partitions 3 --replication-factor 1 --bootstrap-server kafka.flashservice.svc.cluster.local:9093
              echo "Topics created."
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flashservice.svc.cluster.local:9093 --list
  backoffLimit: 5
