apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: flashservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-service
          image: flashservice/worker-service:latest
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_BROKERS
              value: "kafka.flashservice.svc.cluster.local:9093"
            - name: KAFKA_TOPIC
              value: "email-job"
            - name: KAFKA_DLQ_TOPIC
              value: "failed-dlq"
            - name: KAFKA_CONSUMER_GROUP
              value: "worker-service"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: flashservice
spec:
  selector:
    app: worker-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
